---
- name: 'Common packages installation'
  hosts: all
  sudo: true
  roles:
  - common

- name: 'Cassandra nodes installation'
  hosts: cassandra_nodes
  sudo: true
  roles:
  - cassandra

- name: 'Ops Center installation'
  hosts: opscenter_host
  sudo: true
  roles:
  - opscenter

